galaxy_info:
  author: Tsengel-de
  namespace: Tsengel-de
  description: Role for tls
  license: MIT
  min_ansible_version: '2.9'
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
